### ISSUE TITLE
Problem with wrapping gsl function which takes in a work []float

### ISSUE THREAD

**Issue by vinjvinj** [h12w/cwrap#3]
func Spearman(data1 []float64, stride1 int, data2 []float64, stride2 int, n int) (work float64, ret float64) {
       <other lines deleted>

```
_work := (*C.double)(unsafe.Pointer(&work))
_ret := C.gsl_stats_spearman(_data1, _stride1, _data2, _stride2, _n, _work)
ret = float64(_ret)
return
```

}

From the documentation of gsl Spearman (https://www.gnu.org/software/gsl/manual/html_node/Correlation.html) the function definition is:

double gsl_stats_spearman (const double data1[], const size_t stride1, const double data2[], const size_t stride2, const size_t n, double work[])

Additional workspace of size 2*n is required in work. What is the best thing to do here. Do I manually modify the wrapper so that I can pass in the correct size of []float in "work"?

See corresponding golang nuts thread:

https://groups.google.com/forum/#!topic/golang-nuts/vNUqbdP1tpQ

**Comment by vinjvinj** [comment]
There is another problem with the gsl sort package. The problem seems to be where gsl makes changes to an array it is moved from input param to a return variable. However, gsl does not malloc any space and this causes a seg fault. Fix might be as simple as when you come across a non-const double []data just handle it as const double data1[] and let go pass in the array.

**Comment by hailiang** [comment]
For now, just add the function name to the ignore list and write the wrapper manually.

const is an important hint for CWrap guessing. Yes CWrap could use the "safer" approach to ignore "const" and pass everything in parameters, but that will make the wrapper less idiomatic and  useful.

An improvement could be an option for the user to add some annotations to the type declarations.
